-- MySQL Script generated by MySQL Workbench
-- Fri Oct  2 01:00:29 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema esa_battle_sim
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema esa_battle_sim
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `esa_battle_sim` DEFAULT CHARACTER SET utf8 ;
USE `esa_battle_sim` ;

-- -----------------------------------------------------
-- Table `esa_battle_sim`.`armies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `esa_battle_sim`.`armies` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `units` INT NULL,
  `attack_strategy` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `esa_battle_sim`.`battles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `esa_battle_sim`.`battles` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `status` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;